name: Pipeline

on: 
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Show branch
        run: echo "Branch is ${{ github.ref }}"

      - name: Show repository
        run: echo "Repository is ${{ github.repository }}"
  
